
### Main script for calculations ##############################################

source("logging.R")
source("script/100_pre_processing.R")
source("script/200_user_settings.R")
source("script/300_prepare_data.R")
  source("script/401_model_naive.R")
  source("script/402_model_drift.R")
  source("script/403_model_snaive.R")
  source("script/404_model_snaive2.R")
  source("script/405_model_mean.R")
# source("script/406_model_median.R")
  source("script/407_model_tslm.R")
  source("script/408_model_arima.R")
  source("script/409_model_ets.R")
  source("script/410_model_dshw.R")
  source("script/411_model_tbats.R")
  source("script/412_model_dhr-arima.R")
  source("script/413_model_stl-naive.R")
  source("script/414_model_stl-arima.R")
  source("script/415_model_stl-ets.R")
  source("script/416_model_elm.R")
  source("script/417_model_fasster.R")
  source("script/498_model_expert.R")
  source("script/499_model_esn.R")
source("script/500_evaluate_accuracy.R")
source("script/600_post_processing.R")
