
### Main script for calculations ##############################################

source("user_settings_price.R")
# source("user_settings_m4.R")

source("script/100_pre_processing.R")
source("script/200_prepare_data.R")
  source("script/301_model_naive.R")
  source("script/302_model_drift.R")
  source("script/303_model_snaive.R")
  source("script/304_model_snaive2.R")
  source("script/305_model_mean.R")
  source("script/306_model_median.R")
  source("script/307_model_tslm.R")
  source("script/308_model_arima.R")
  source("script/309_model_ets.R")
  source("script/310_model_theta.R")
  source("script/311_model_dshw.R")
  source("script/312_model_tbats.R")
  source("script/313_model_dhr_arima.R")
  source("script/314_model_stl_naive.R")
  source("script/315_model_stl_arima.R")
  source("script/316_model_stl_ets.R")
  source("script/317_model_elm.R")
  source("script/318_model_fasster.R")
  source("script/397_model_arx.R")
  source("script/398_model_expert.R")
  source("script/399_model_esn.R")
source("script/400_evaluate_accuracy.R")
source("script/500_post_processing.R")
